name: Test, Linting & Type-check

on:
  push:
    branches: 
      - master 
      - release/*

  pull_request:
    branches:
      - release/*

jobs:
  test:
    name: Test, Lint and Type-check
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Dependencies 
      run: yarn --frozen-lockfile
    - name: Run Test using Jest
      run: yarn test --ci
    - name: Lint Code using Eslint
      run: yarn lint
    - name: Type-check Code using Typescript
      run: yarn type-check
