name: Test

on:
  push:
    branches: 
      - master 
      - v[12].[0-9]+.[0-9]+-(alpha\b|beta\b|rc\b)

  pull_request:
    branches:
      - master 
      - v[12].[0-9]+.[0-9]+-(alpha\b|beta\b|rc\b)

jobs:
  test:
    name: Test using Jest
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Dependencies 
      run: yarn --frozen-lockfile
    - name: Run Test using Jest
      run: yarn test
